"""Application-wide constants."""

DEFAULT_PROMPT_VERSION = "persona-v2.1"
MIN_CANDIDATE_CONFIDENCE = 0.45
MAX_MEMORY_RANK_LINES = 6
MAX_MEMORY_INJECT_LINES = 3
MAX_CALENDAR_VISITS = 6
MAX_CARE_STAFF_NOTES = 5
MAX_CARE_MEMORY_NOTES = 4
